---
name: Update latest posts

on:
  workflow_dispatch:

jobs:
  update-readme:
    name: Update README with latest videos and posts from youtube and dev.to
    runs-on: ubuntu-latest
    steps:
      - name: Source checkout
        uses: actions/checkout@v2.4.0

      - name: Update dev community posts
        uses: gautamkrishnar/blog-post-workflow@1.6.3
        with:
          comment_tag_name: DEVDOTTO
          max_post_count: 20
          feed_list: "https://dev.to/feed/tomerfi"
          commit_message: "updated readme with the latest dev.to posts"
